versions:
  current: 1.18.0
  previous: 1.17.1
  previous_range: 1.17.0
  channel: pipelines-1.18
  openshift:
    latest: 4.18 # lastest GA'ed openshift
    min: 4.15 # Minimum version OSP supports
images:
  # tektoncd-pipeline
  - name: IMAGE_PIPELINES_TEKTON_PIPELINES_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/controller@sha256:dc82ab2355589d32c4a0d38fa908703d17c66d68047e27835993e4492a1cd48e
  - name: IMAGE_PIPELINES_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/webhook@sha256:e1aab634e2a2173e7ed9b9b488d383b0b1fb3b02dff07b1ab0c35bb706e837cb
  - name: IMAGE_PIPELINES_CONTROLLER # should be RESOLVERS instead
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/resolvers@sha256:a561f96a75d529fcec6632a0701ab624b8a0bdf67737a9ac6ce72633a50442f1
  - name: IMAGE_PIPELINES_TEKTON_EVENTS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/events@sha256:99b685cbce3c8c20ba7b36d8ae5d4b36d47f9a0fd910c759f373ae2691374f76
  - name: IMAGE_PIPELINES_ARG__ENTRYPOINT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/entrypoint@sha256:31d1f951e31145d9bb41706f960a58d0f42e6ce1102376d9058bcfb20d576be4
  - name: IMAGE_PIPELINES_ARG__WORKINGDIRINIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/workingdirinit@sha256:65ffd2a18c22d4b239e6eaf3b3e8a726f06d0ae2ec4cb6405cbd9c9243397e24
  - name: IMAGE_PIPELINES_ARG__NOP_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/nop@sha256:623f2d7bde10c9dcbe8025f52ac4e431637d8036138c76c6337d3aa9713a415e
  - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/entrypoint@sha256:31d1f951e31145d9bb41706f960a58d0f42e6ce1102376d9058bcfb20d576be4
  - name: IMAGE_PIPELINES_ARG__SIDECARLOGRESULTS_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-pipeline-1-18/sidecarlogresults@sha256:73858dfa35a449adbbef5fa2df6214c23ae9583e58071d539cc3757b019ab70c
  # tektoncd-triggers
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-1-18/controller@sha256:54d75042b99f31cd3f473793f4a3d0b3c992de6a0c2bde6021917f6ff92cdd7e
  - name: IMAGE_TRIGGERS_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-1-18/webhook@sha256:cc577c518adad3e3ddab92447a84d921cef1fc96116901eaa4f51db8e382a26d
  - name: IMAGE_TRIGGERS_TEKTON_TRIGGERS_CORE_INTERCEPTORS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-1-18/core-interceptors@sha256:08142d0e9ad239151f2c9e804d026661d74105603f9de575e714ccd4e21c45df
  - name: IMAGE_TRIGGERS_ARG__EL_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-triggers-1-18/eventlistenersink@sha256:b2dd24f5409873ff5e535a0983b8b525db951911d9f484f2cdca82d00da12992
  # tektoncd-chains
  - name: IMAGE_CHAINS_TEKTON_CHAINS_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-chains-1-18/controller@sha256:e14c8975eb51a10006bd21410b5432f92dda1056579fcb80d3c1bd93b33a7bb3
  # tektoncd-hub
  - name: IMAGE_HUB_TEKTON_HUB_DB_MIGRATION
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-1-18/db-migration@sha256:09f17df08f0ad815bd4f9d916ccbdbc2e49ff3d41c4108e66d63d1787c3d8003
  - name: IMAGE_HUB_TEKTON_HUB_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-1-18/hub-api@sha256:53ab379de5e18d1d5709fa124ce612b733a1ec4208880b51d1da02e344c74c92
  - name: IMAGE_HUB_TEKTON_HUB_UI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-hub-1-18/hub-ui@sha256:a584a0ac96c14acf11c9fa48a744362242ec80a8f9cb2b22c6ea9e91508b36af
  # tektoncd-results
  - name: IMAGE_RESULTS_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-1-18/watcher@sha256:1c18a5db61ef3fec9b0a49fbd35fa313b01ce98f3c5a26015487459c9f5bd63d
  - name: IMAGE_RESULTS_API
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-1-18/api@sha256:7488c5d75d5d90b304b8e26dd98c2a2131f201a5b183069315aaf21275468d12
  - name: IMAGE_RESULTS_RETENTION_POLICY_AGENT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-results-1-18/retention-policy-agent@sha256:bfd97905654b84171de4022fab9c5fbc3bee80669a8080f7bf4c11af7c8b7b0d
  - name: IMAGE_RESULTS_POSTGRES
    value: registry.redhat.io/rhel8/postgresql-13@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
  # tektoncd-cli
  - name: IMAGE_JOB_PRUNER_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-1-18/tkn@sha256:195f94b904b4797802915704058c5b00798abddc8735a5a7dd9752176feaa3a7
  - name: IMAGE_ADDONS_PARAM_TKN_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-1-18/tkn@sha256:195f94b904b4797802915704058c5b00798abddc8735a5a7dd9752176feaa3a7
  - name: IMAGE_ADDONS_TKN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-1-18/tkn@sha256:195f94b904b4797802915704058c5b00798abddc8735a5a7dd9752176feaa3a7
  - name: IMAGE_ADDONS_TKN_CLI_SERVE # FIXME: we need to figure how to manage this in konflux. For now, using released version (1.16)
    # value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-cli-1-18/serve-tkn@sha256:42eed05d0f681deb8d9198bf483bbeda02016c23515f061b828aec71f0ae142f
    value: registry.redhat.io/openshift-pipelines/pipelines-serve-tkn-cli-rhel8@sha256:cc5234d6a6afc213d24786253c8ea70bb77f3f5c3e1ea1526debb8a1776e4ffc
  # manual-approval-gate
  - name: IMAGE_MAG_MANUAL_APPROVAL
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-1-18/webhook@sha256:60de005aea3795e6479fa9deb4e65dcf04ccbfa8d20ecc58ea8462ecf27226e8
  - name: IMAGE_MAG_TEKTON_TASKGROUP_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/manual-approval-gate-1-18/controller@sha256:2d0944ce9e785fb2a13a35e34572867ecf2e0c8fdfb2d77bcd607a5f1e8231a0
  # pipelines-as-code
  - name: IMAGE_PAC_PAC_CONTROLLER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-1-18/controller@sha256:15867d2338cd3d1547aa3024370664ac8090ca7f5af4ac82964bc6db29aabc20
  - name: IMAGE_PAC_PAC_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-1-18/webhook@sha256:c2c74619cc7413b16a017aab396de84ec07cd875f1bee5fed6ef763f8af616fa
  - name: IMAGE_PAC_PAC_WATCHER
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-1-18/watcher@sha256:1949fea95b521e28328535cb492c08548a9873346103414d432536dec57a30ad
  - name: IMAGE_PAC_PAC_CLI
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/pac-downstream-1-18/cli@sha256:d99969c1112ee8914eb3e9b9031eb697018f2f295c775264a2c9904e1ec66ab7
  # operator
  - name: OPENSHIFT_PIPELINES_OPERATOR_LIFECYCLE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-1-18/operator@sha256:192157a057ed1bf3de4cc9043f07e32f2d50aae62b87980044d47bb755d6f374
  - name: OPENSHIFT_PIPELINES_OPERATOR_CLUSTER_OPERATIONS
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-1-18/operator@sha256:192157a057ed1bf3de4cc9043f07e32f2d50aae62b87980044d47bb755d6f374
  - name: IMAGE_PIPELINES_PROXY
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-1-18/proxy@sha256:8a9d55690e10edc3b9c04c79fe997bd857e8ae46028729283772c6f54346cda1
  - name: TEKTON_OPERATOR_WEBHOOK
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/operator-1-18/webhook@sha256:7d697734eae15ec2f419bd300c1ff479f43333f881b8d5dbe4a449171e30c5ae
  # cache
  - name: IMAGE_ADDONS_CACHE_UPLOAD
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tekton-caches-1-18/cache@sha256:b0d95cccd145f7f00f82510c1b8f7bca6a923f6f4a53fb037d05b9c17a46f5f2
  - name: IMAGE_ADDONS_CACHE_FETCH
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tekton-caches-1-18/cache@sha256:b0d95cccd145f7f00f82510c1b8f7bca6a923f6f4a53fb037d05b9c17a46f5f2
  # Addons
  - name: IMAGE_PIPELINES_ARG__GIT_IMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-18/git-init@sha256:75c5ff183c5cdba54c4db0599047794b796a3b445f0b3f61336f2e1e00e447e7
  - name: IMAGE_ADDONS_PARAM_GITINITIMAGE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-18/git-init@sha256:75c5ff183c5cdba54c4db0599047794b796a3b445f0b3f61336f2e1e00e447e7
  - name: IMAGE_ADDONS_GIT_RUN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-18/git-init@sha256:75c5ff183c5cdba54c4db0599047794b796a3b445f0b3f61336f2e1e00e447e7
  - name: IMAGE_ADDONS_REPORT
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-18/git-init@sha256:75c5ff183c5cdba54c4db0599047794b796a3b445f0b3f61336f2e1e00e447e7
  - name: IMAGE_ADDONS_GIT_CLONE
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/ecosystem-images-1-18/git-init@sha256:75c5ff183c5cdba54c4db0599047794b796a3b445f0b3f61336f2e1e00e447e7
  - name: IMAGE_ADDONS_KN
    value: registry.redhat.io/openshift-serverless-1/client-kn-rhel8@sha256:a5a7b2be50f211d4d9d555b2a2e2302096c139ff5011d984cc386f1530007f16
  - name: IMAGE_ADDONS_SKOPEO_RESULTS
    value: registry.redhat.io/rhel8/skopeo@sha256:1dcb4189c92da21ee58b3ca5433615e0208194c8412f7f1fb45fa491179aaf9b
  - name: IMAGE_ADDONS_BUILD
    value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
  - name: IMAGE_ADDONS_S2I_BUILD
    value: registry.redhat.io/rhel8/buildah@sha256:5c7cd7c9a3d49e8905fc98693f6da605aeafae36bde5622dc78e12f31db3cd59
  - name: IMAGE_ADDONS_S2I_GENERATE
    value: registry.redhat.io/source-to-image/source-to-image-rhel8@sha256:6a6025914296a62fdf2092c3a40011bd9b966a6806b094d51eec5e1bd5026ef4
  - name: IMAGE_ADDONS_LOAD_SCRIPTS
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_MAVEN_GENERATE
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_PREPARE
    value: registry.redhat.io/ubi8/ubi-minimal@sha256:a47c89f02b39a98290f88204ed3d162845db0a0c464b319c2596cfd1e94b444e
  - name: IMAGE_ADDONS_MAVEN_GOALS
    value: registry.redhat.io/ubi8/openjdk-17@sha256:632e78989471859ca4ed1148b951a911f7e3b6e6516482be20967c4171612c55
  - name: IMAGE_PIPELINES_CONSOLE_PLUGIN
    value: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/console-plugin-1-18/console-plugin@sha256:b04589b0d8d28230f32e347715a33ec2876fd5dad3611864c6e98d883bcd7422
